# Generated by Django 5.0.6 on 2024-05-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_annonce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annonce',
        ),
    ]
