# Generated by Django 5.0.6 on 2024-05-17 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0005_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='official_homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('D', 'Disques'), ('V', 'Vetements'), ('A', 'Affiche')], default='D', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
            preserve_default=False,
        ),
    ]
