# Generated by Django 5.0.6 on 2024-05-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0006_annonce_description_annonce_official_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='liste.band'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('D', 'Disques'), ('V', 'Vetements'), ('A', 'Affiche'), ('DI', 'Divers')], max_length=20),
        ),
    ]
